# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.astradia
archives_base_name=astradia-project
server_version=1.1.0
client_version=1.1.1
common_version=1.1.3

# Dependencies
fabric_version=0.141.3+1.21.11