import java.text.SimpleDateFormat

version = project.server_version
group = project.maven_group

dependencies {
	def isDevRun = gradle.startParameter.taskNames.any {
		it.contains("run")
	}

	if (isDevRun) {
		implementation(project(path: ":astradia-common", configuration: "namedElements"))
	} else {
		include(modImplementation(project(":astradia-common")))
	}

	modImplementation(include("org.mongodb:bson:4.11.1"))
	modImplementation(include("org.mongodb:mongodb-driver-core:4.11.1"))
	modImplementation(include("org.mongodb:mongodb-driver-sync:4.11.1"))
}

loom {
	runConfigs.configureEach {
		ideConfigGenerated(true)
	}
}

processResources {
	def properties = [
			"version"   : project.version,
			"buildDate" : new SimpleDateFormat("yyyyMMdd").format(new Date())
	]

	inputs.properties(properties)

	filesMatching("fabric.mod.json") {
		expand(properties)
	}
}