import java.text.SimpleDateFormat

plugins {
    id 'java'
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id "org.jetbrains.kotlin.jvm" version "2.1.0"
}

version = project.client_version
group = project.maven_group

repositories {
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup("software.bernie.geckolib")
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    def isDevRun = gradle.startParameter.taskNames.any {
        it.contains("run")
    }

    if (isDevRun) {
        implementation(project(path: ":astradia-common", configuration: "namedElements"))
    } else {
        include(modImplementation(project(":astradia-common")))
    }


//    include(modImplementation(project(":astradia-common")))

    include(modImplementation("software.bernie.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"))
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

}

loom {
    runConfigs.configureEach {
        ideConfigGenerated(true)
    }
    accessWidenerPath = file("src/main/resources/astradia-client.accesswidener")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
// if it is present.
// If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

tasks.named("remapJar").configure {
    dependsOn(":astradia-common:remapJar")
}

processResources {
    def properties = [
            "version"   : project.version,
            "buildDate" : new SimpleDateFormat("yyyyMMdd").format(new Date())
    ]

    inputs.properties(properties)

    filesMatching("fabric.mod.json") {
        expand(properties)
    }
}
